# -*- coding: utf-8 -*-
"""ejercicio8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8pxXGyaMuqr3ipRGpSoiY5-pw4fEHoV
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Guardar el DataFrame en un archivo CSV
data = pd.read_csv('/content/drive/MyDrive/parcial1/ejercicio8.csv')
import pandas as pd
import math
# Mi clase será talla, ya que con altura y peso podemos determinar qué talla puede serle útil a una persona
# Función para calcular la entropía de un conjunto de datos
def calcular_entropia(columna):
    # Calcular la frecuencia de cada valor
    frecuencias = columna.value_counts(normalize=True)
    # Calcular la entropía usando la fórmula
    entropia = -sum(frecuencias * [math.log2(1/p) for p in frecuencias])
    return entropia

# Función para calcular la ganancia de información de un atributo respecto a la clase
def calcular_ganancia(df, atributo, clase):
    # Calcular la entropía inicial del conjunto
    entropia_inicial = calcular_entropia(df[clase])

    # Calcular la entropía ponderada del atributo
    valores_atributo = df[atributo].unique()
    entropia_atributo = 0
    for valor in valores_atributo:
        subconjunto = df[df[atributo] == valor]
        entropia_subconjunto = calcular_entropia(subconjunto[clase])
        ponderacion = len(subconjunto) / len(df)
        entropia_atributo += ponderacion * entropia_subconjunto

    # Calcular la ganancia de información
    ganancia_informacion = entropia_inicial - entropia_atributo
    return ganancia_informacion

# Calcular la entropía de la clase "Clase"
entropia_clase = calcular_entropia(df['Clase'])
print(f"Entropía de la clase 'Clase': {entropia_clase}")

# Calcular la ganancia de información para cada atributo
ganancia_altura = calcular_ganancia(df, 'Altura', 'Clase')
ganancia_peso = calcular_ganancia(df, 'Peso', 'Clase')
ganancia_talla = calcular_ganancia(df, 'Talla', 'Clase')

# Mostrar los resultados
print(f"Ganancia de información para 'Altura': {ganancia_altura}")
print(f"Ganancia de información para 'Peso': {ganancia_peso}")
print(f"Ganancia de información para 'Talla': {ganancia_talla}")