# -*- coding: utf-8 -*-
"""ejercicio8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8pxXGyaMuqr3ipRGpSoiY5-pw4fEHoV
"""

from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

# Guardar el DataFrame en un archivo CSV
data = pd.read_csv('/content/drive/MyDrive/parcial1/ejercicio8.csv')
import pandas as pd
import math

def calcular_entropia(columna):
    frecuencias = columna.value_counts(normalize=True)
    entropia = -sum(frecuencias * [math.log2(p) for p in frecuencias])
    return entropia

def calcular_ganancia(df, atributo, clase):
    entropia_inicial = calcular_entropia(df[clase])

    # Calcular la entropía ponderada del atributo
    valores_atributo = df[atributo].unique()
    entropia_atributo = 0
    for valor in valores_atributo:
        subconjunto = df[df[atributo] == valor]
        entropia_subconjunto = calcular_entropia(subconjunto[clase])
        ponderacion = len(subconjunto) / len(df)
        entropia_atributo += ponderacion * entropia_subconjunto

    # Calcular la ganancia de información
    ganancia_informacion = entropia_inicial - entropia_atributo
    return ganancia_informacion

# Calcular la entropía de la clase "Talla"
entropia_talla = calcular_entropia(df['Talla'])
print(f"Entropía de la clase 'Talla': {entropia_talla}")

# Calcular la ganancia de información para los atributos "Altura" y "Peso"
ganancia_altura = calcular_ganancia(df, 'Altura', 'Talla')
ganancia_peso = calcular_ganancia(df, 'Peso', 'Talla')

# Mostrar los resultados
print(f"Ganancia de información para 'Altura': {ganancia_altura}")
print(f"Ganancia de información para 'Peso': {ganancia_peso}")