# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JaqwakR_iM-O6L-0VAKwWUS1nny5sqC1
"""

from google.colab import drive
drive.mount("/content/drive")
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/parcial1/nivelestres.csv', index_col=0)